### ISSUE TITLE
スロットリングの制限回数

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/TwoFactorAuthCustomerSms42#11]
limitが30に設定されていますが何か意図ありますか？
https://github.com/EC-CUBE/TwoFactorAuthCustomerSms42/blob/main/Resource/config/services.yaml#L11

TwoFactorAuthCustomer42では5回になっているため、合わせてもよいかと思いました。
https://github.com/EC-CUBE/TwoFactorAuthCustomer42/blob/main/Resource/config/services.yaml#L11

**Comment by chihiro-adachi** [comment]
@KenTanaka @sai-gillingham

**Comment by sai-gillingham** [comment]
@chihiro-adachi 

レビューして頂いてありがとうございます！

新しいプルリクで
SMSプラグインの試行回数をTwoFactorAuthCustomer42の試行回と合わせましたので、プルリクのレビューを頂けますか？

https://github.com/EC-CUBE/TwoFactorAuthCustomerSms42/pull/12
